name: post-release

on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: CCBR/actions/post-release@copilot/support-r-package-structure
        with:
          github-token: ${{ github.token }}
          update-sliding-tags: false
          ccbr-actions-version: copilot/support-r-package-structure
